name: NHL PP1 Tracker

on:
  schedule:
    - cron: "*/10 * * * *"  # runs every 10 minutes
  workflow_dispatch:        # allows manual run

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4 lxml requests

      - name: Run PP1 Tracker
        run: |
          python pp1_tracker.py
